In [6]:
import cv2
import numpy as np
from scipy.signal import convolve2d
from scipy.ndimage.filters import correlate 
import matplotlib.pyplot as plt
import matplotlib.image as pltimg 
import math
import skimage
from scipy.ndimage.filters import gaussian_laplace

In [7]:
def load_image(path):
    '''
    :param path: path to load image
    :return: grayscaled and float image
    '''
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    # transmit the image to float
    img = skimage.img_as_float(img)
    print(img.dtype)
    return img

In [8]:
def normalize(img):
    ''' Function to normalize an input array to 0-1 '''
    img_min = img.min()
    img_max = img.max()
    return (img - img_min) / (img_max - img_min)

def generate_laplacian_filter(size, sigma):
    return gaussian_laplace(np.zeros((size,size)),sigma=sigma)

In [9]:
def show_all_circles(image, cx, cy, rad, color='r'):
    """
    image: numpy array, representing the grayscsale image
    cx, cy: numpy arrays or lists, centers of the detected blobs
    rad: numpy array or list, radius of the detected blobs
    """
    import matplotlib.pyplot as plt
    from matplotlib.patches import Circle

    fig, ax = plt.subplots()
    ax.set_aspect('equal')
    ax.imshow(image, cmap='gray')
    for x, y, r in zip(cx, cy, rad):
        circ = Circle((x, y), r, color=color, fill=False)
        ax.add_patch(circ)

    plt.title('%i circles' % len(cx))
    plt.show()

In [10]:
# define parameters
'''
k           increasing factor K
levels      number of iterations
ini_sigma   scale for LOG
'''
threshold = 0.25              
k = 1.25                     
levels = 12                    
initial_sigma = 2            
sigma = 2

BUFFER_FLY = "data\\part2\\butterfly.jpg" 
EINSTEIN = "data\\part2\\einstein.jpg"
FISHES = "data\\part2\\fishes.jpg"
SUNFLOWERS =  "data\\part2\\sunflowers.jpg"

In [16]:
# upscaling

def upscaling_method(img, sigma, k, levels):
    height, width = img.shape
    print(height, width)
    img_scale_space = np.zeros(height, width, levels)
    
    for i in range(levels):
        # element wise scaling
        img_scale_space = np.power(gaussian_laplace(img, sigma=sigma) * sigma**2, 2)
        sigma = sigma * k
    
    suppressed_space = zeros(height, width, levels)
    
    # nonmaximum supression in each 2d slice
    for i in range(levels)
        suppressed_space = 

    

In [15]:
# downsampling
a = gaussian_laplace(np.ones((3,3)),sigma=1)
print(a)

[[-0.000144 -0.000144 -0.000144]
 [-0.000144 -0.000144 -0.000144]
 [-0.000144 -0.000144 -0.000144]]
